# Dockerfile.bind9
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y bind9 bind9utils bind9-doc

COPY zones /etc/bind/zones
COPY named.conf.local /etc/bind/named.conf.local

EXPOSE 53/udp
EXPOSE 53/tcp

CMD ["named", "-g", "-c", "/etc/bind/named.conf"]
