FROM nginx

ARG app_name="APP1"

RUN apt update && apt install -y curl

COPY nginx.conf /etc/nginx/nginx.conf

RUN sed -i 's/$$app_name/'"${app_name}"'/g' /etc/nginx/nginx.conf

RUN echo $app_name > /usr/share/nginx/html/index.html

CMD ["nginx", "-g", "daemon off;"]
