services:
  bind9:
    build:
      context: .
      dockerfile: Dockerfile.bind9
    container_name: bind9
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./zones:/etc/bind/zones
      - ./named.conf.local:/etc/bind/named.conf.local
    networks:
      mynet:
        ipv4_address: 172.19.0.2

  app1:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - app_name=app1
    container_name: app1
    depends_on:
      - bind9
    ports:
      - "8081:80"
    expose:
      - "80"
    dns:
      - 172.19.0.2
    networks:
      mynet:
        ipv4_address: 172.19.0.3

  app2:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - app_name=app2
    container_name: app2
    depends_on:
      - bind9
    ports:
      - "8080:80"
    expose:
      - "80"
    dns:
      - 172.19.0.2
    networks:
      mynet:
        ipv4_address: 172.19.0.4

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"