services:
  ns1:
    build:
      context: .
      dockerfile: Dockerfile.bind9
      args:
        - nameserver=ns1
    container_name: ns1
    volumes:
      - ./zones:/etc/bind/zones
      - ./named.conf.local.ns1:/etc/bind/named.conf.local
    networks:
      net1:
        ipv4_address: 172.19.0.2
      net2:
        ipv4_address: 172.20.0.3
  
  ns2:
    build:
      context: .
      dockerfile: Dockerfile.bind9
      args:
        - nameserver=ns2
    container_name: ns2
    volumes:
      - ./zones:/etc/bind/zones
      - ./named.conf.local.ns2:/etc/bind/named.conf.local
    networks:
      net1:
        ipv4_address: 172.19.0.5

  ns3:
    build:
      context: .
      dockerfile: Dockerfile.bind9
      args:
        - nameserver=ns3
    container_name: ns3
    volumes:
      - ./named.conf.local.ns3:/etc/bind/named.conf.local
    networks:
      net2:
        ipv4_address: 172.20.0.2

  app1:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - app_name=app1
    container_name: app1
    depends_on:
      - ns1
      - ns2
    expose:
      - "80"
    dns:
      - 172.19.0.2
      - 172.19.0.5
      - 172.20.0.2
    networks:
      net1:
        ipv4_address: 172.19.0.3
      net2:
        ipv4_address: 172.20.0.4

  app2:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - app_name=app2
    container_name: app2
    depends_on:
      - ns1
      - ns2
    expose:
      - "80"
    dns:
      - 172.19.0.2
      - 172.19.0.5
      - 172.20.0.2
    networks:
      net1:
        ipv4_address: 172.19.0.4

networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
  net2:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"