services:
  ns1:
    build:
      context: .
      dockerfile: Dockerfile.bind9
      args:
        - nameserver=ns1
    container_name: ns1
    volumes:
      - ./zones:/etc/bind/zones
      - ./named.conf.local.ns1:/etc/bind/named.conf.local
    networks:
      mynet:
        ipv4_address: 172.19.0.2
  
  ns2:
    build:
      context: .
      dockerfile: Dockerfile.bind9
      args:
        - nameserver=ns2
    container_name: ns2
    volumes:
      - ./zones:/etc/bind/zones
      - ./named.conf.local.ns2:/etc/bind/named.conf.local
    networks:
      mynet:
        ipv4_address: 172.19.0.5

  app1:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - app_name=app1
    container_name: app1
    depends_on:
      - ns1
      - ns2
    expose:
      - "80"
    dns:
      - 172.19.0.2
      - 172.19.0.5
    networks:
      mynet:
        ipv4_address: 172.19.0.3

  app2:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - app_name=app2
    container_name: app2
    depends_on:
      - ns1
      - ns2
    expose:
      - "80"
    dns:
      - 172.19.0.2
      - 172.19.0.5
    networks:
      mynet:
        ipv4_address: 172.19.0.4

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"